In [1]:
from precomputed_python import AnnotationReader, morton_code_to_gridpt, compressed_morton_code
import numpy as np
import pandas as pd
import asyncio
import tensorstore as ts
from neuroglancer import viewer_state

In [2]:
# pre_ann=AnnotationReader("gs://neuroglancer-20191211_fafbv14_buhmann2019_li20190805")
# ann_id= 15959574
# ann = pre_ann.get_by_id(ann_id)

pre_ann = AnnotationReader("gs://allen_neuroglancer_ccf/merscope_ccffix_1")
ann_id= 1813224
ann = pre_ann.get_by_id(1813224)


I0402 14:40:13.748974 9570268 google_auth_provider.cc:149] Using credentials at /Users/forrestc/.config/gcloud/application_default_credentials.json
I0402 14:40:13.752517 9570268 google_auth_provider.cc:156] Using OAuth2 AuthProvider


In [3]:
ann

{'regionset_1_cluster_idx': np.int32(64),
 'regionset_2_cluster_idx': np.int32(261),
 'regionset_3_cluster_idx': np.int32(449),
 'neurotransmitter': 'Glut',
 'class': '18 TH Glut',
 'subclass': '154 PF Fzd5 Glut',
 'supertype': '0675 PF Fzd5 Glut_2',
 'cluster': '2722 PF Fzd5 Glut_2',
 'neurotransmitter_color': array([ 43, 147, 223], dtype=uint8),
 'class_color': array([ 13,  71, 161], dtype=uint8),
 'subclass_color': array([ 28,   0, 153], dtype=uint8),
 'supertype_color': array([ 69,  69, 153], dtype=uint8),
 'cluster_color': array([ 15, 102,  16], dtype=uint8),
 'regionset_1_cluster_color': array([218, 149, 255], dtype=uint8),
 'regionset_2_cluster_color': array([255, 126, 209], dtype=uint8),
 'regionset_3_cluster_color': array([230, 175,   0], dtype=uint8),
 'padding46': array([0, 0], dtype=uint8),
 'ccf_ids': array([997,   8, 549, 362], dtype=uint64),
 'cluster_annotation_index': array([4304, 1056,  197,   27,    0], dtype=uint64),
 'point': array([7347.7915, 3566.362 , 6301.7676]

In [35]:
pre_ann.read_annotations_in_chunk('spatial0', chunk_index=[3,1,8])

injection_volume        transgenic_line structure_abbrev  \
ID                                                                    
546103149          0.187840          Emx1-IRES-Cre             VISp   
536299435          0.148784          Emx1-IRES-Cre             VISp   
530574594          0.097888         Rbp4-Cre_KL100             VISp   
479755622          0.168528          Emx1-IRES-Cre             VISp   
479756361          0.163775          Emx1-IRES-Cre             VISp   
502966396          0.096802          Emx1-IRES-Cre             VISp   
479701339          0.132360          Emx1-IRES-Cre             VISp   
479983421          0.222693          Emx1-IRES-Cre             VISp   
562061175          0.070026          Emx1-IRES-Cre             VISp   
501004474          0.210919          Emx1-IRES-Cre             VISp   
500836840          0.375218          Emx1-IRES-Cre             VISp   
596253012          0.065162         Rbp4-Cre_KL100             VISp   
523718823          0.075229         Rbp4-Cre_KL100            VISpm   
482578964          0.043192         Rbp4-Cre_KL100             VISp   
531441947          0.059738          Tlx3-Cre_PL56             VISp   
526515319          0.083915           Ai75(RCL-nT)             VISp   
557342452          0.099422        Ntsr1-Cre_GN220            VISpm   
546389260          0.093664           Ai75(RCL-nT)             VISp   
540146149          0.039305          Tlx3-Cre_PL56             VISp   
539739321          0.084314        Ntsr1-Cre_GN220             VISp   
501786400          0.093047           Ai75(RCL-nT)             VISp   
523714193          0.098124        Ntsr1-Cre_GN220             VISp   
503069254          0.071099         Rbp4-Cre_KL100             VISp   
501116471          0.233435          Cux2-IRES-Cre             VISp   
478257959          0.067571        Ntsr1-Cre_GN220             VISp   
483013787          0.072115          Cux2-IRES-Cre             VISp   
522408611          0.030385          Tlx3-Cre_PL56             VISp   
501711996          0.094308           Ai75(RCL-nT)             VISp   
495877413          0.036151           Ai75(RCL-nT)             VISp   
524656772          0.080185          Cux2-IRES-Cre             VISp   
478256439          0.026422  A930038C07Rik-Tg1-Cre             VISp   
561918178          0.063352           Ai75(RCL-nT)             VISp   
503809372          0.016398         Rbp4-Cre_KL100             VISp   
565146821          0.049445           Ai75(RCL-nT)             VISp   
514313871          0.026162        Ntsr1-Cre_GN220             VISp   
495753765          0.031881        Ntsr1-Cre_GN220             VISp   
584507699          0.014913  A930038C07Rik-Tg1-Cre             VISp   
517072832          0.011313         Rbp4-Cre_KL100             VISp   
574637452          0.015745           Ai75(RCL-nT)             VISp   
545799841          0.004239           Ai75(RCL-nT)             VISp   
504099316          0.013981         Scnn1a-Tg3-Cre             VISp   
563731437          0.012798           Ai75(RCL-nT)             VISp   
501787135          0.011435           Ai75(RCL-nT)             VISp   
566992832          0.003263         Rbp4-Cre_KL100             VISp   
479085232          0.005350         Scnn1a-Tg3-Cre             VISp   
496252297          0.010524  A930038C07Rik-Tg1-Cre             VISp   
501923898          0.011038           Ai75(RCL-nT)             VISp   
563352720          0.004824           Ai75(RCL-nT)             VISp   
502592260          0.003796           Ai75(RCL-nT)             VISp   
485553574          0.002349           Ai75(RCL-nT)             VISp   
515920693          0.002208           Ai75(RCL-nT)             VISp   
601486918          0.002457          Sim1-Cre_KJ18             VISp   
539511058          0.000730           Ai75(RCL-nT)             VISp   
528964707          0.001641           Ai75(RCL-nT)             VISp   
526784559          0.000781        

In [11]:
lb=np.array((115, 36, 49))*pre_ann.info['spatial'][-1]['chunk_size']+pre_ann.info['lower_bound']
up=np.array((116, 37, 50))*pre_ann.info['spatial'][-1]['chunk_size']+pre_ann.info['lower_bound']
lb,up

(array([436191.71484375, 160873.03125   , 216406.390625  ]),
 array([439646.390625 , 164330.7265625, 220822.03125  ]))

In [14]:
lower_bound, upper_bound

(array([436340., 163832., 216580.]), array([436504., 163972., 216780.]))

In [13]:
(lower_bound-pre_ann.info['lower_bound'])/pre_ann.info['spatial'][-1]['chunk_size']

array([115.04292303,  36.8557633 ,  49.03931692])

In [6]:
df

cleft_score        score         id  autapse  \
ID                                                        
151117838        142.0   260.028564  151117838        0   
168781706        142.0    65.476616  168781706        0   
15959534         144.0  1753.234131   15959534        0   
149695143          0.0    71.399132  149695143        1   
15962282         155.0    51.330456   15962282        0   
149697785        141.0     8.575776  149697785        0   
167501330          0.0    30.044559  167501330        0   
234627924          0.0     8.628290  234627924        0   
149695085         66.0   125.309219  149695085        0   
151117841         88.0    23.121716  151117841        0   
149695111        147.0   240.156509  149695111        0   
15959535         148.0   645.653015   15959535        0   
149697685        147.0   458.759064  149697685        0   
149697750        177.0   238.063629  149697750        0   
149697792          0.0   147.827576  149697792        0   
149695078        151.0    19.109560  149695078        0   
234627925          0.0    87.521248  234627925        0   
151117864        149.0   118.887077  151117864        0   
149695160         38.0     6.673315  149695160        0   
151117840         47.0    45.219440  151117840        1   
149697662        163.0   280.212372  149697662        0   
149697783        107.0     5.719281  149697783        0   
149695173        120.0   298.771881  149695173        0   
149695176          0.0    35.774788  149695176        0   
149695130        156.0   525.773315  149695130        0   
149697707        137.0    67.278831  149697707        0   
149697654        146.0   481.283295  149697654        0   
149697736        175.0   120.548477  149697736        0   
15962275         154.0   432.792511   15962275        0   
149697715         36.0   147.874100  149697715        0   
149695150          0.0     8.576214  149695150        1   
151117856        147.0    28.880575  151117856        0   
151117845          8.0    30.013735  151117845        0   
15962262         128.0   522.173706   15962262        0   
167501337          0.0    47.588146  167501337        0   
151117857         66.0    41.782108  151117857        0   
149695165        104.0    23.008419  149695165        0   
149697784        145.0   378.528839  149697784        0   
15962278         155.0   314.426514   15962278        0   
167503334          0.0    19.239094  167503334        1   
149695029        162.0   285.251190  149695029        0   
15962291         161.0    83.574120   15962291        0   
15962298         146.0   882.072388   15962298        0   
15962271           0.0    41.214767   15962271        1   
15962290         145.0    25.000849   15962290        0   
149697745        177.0    23.996632  149697745        0   
151117835        131.0     8.596482  151117835        0   
15962308          88.0   185.134155   15962308        0   

                                  point_a                         point_b  
ID                                                                         
151117838  [438596.0, 161348.0, 217680.0]  [438508.0, 161248.0, 217640.0]  
168781706  [436840.0, 161228.0, 218760.0]  [436816.0, 161136.0, 218720.0]  
15959534   [437260.0, 163760.0, 216520.0]  [437168.0, 163712.0, 216520.0]  
149695143  [436588.0, 163448.0, 217960.0]  [436528.0, 163496.0, 217960.0]  
15962282   [437976.0, 162604.0, 216560.0]  [438104.0, 162656.0, 216560.0]  
149697785  [438708.0, 163176.0, 217840.0]  [438696.0, 163324.0, 217840.0]  
167501330  [437372.0, 163440.0, 218600.0]  [437288.0, 163436.0, 218680.0]  
234627924  [438520.0, 161476.0, 220400.0]  [438640.0, 161536.0, 220400.0]  
149695085  [436884.0, 163980.0, 217400.0]  [436856.0, 163900.0, 217360.0]  
151117841  [439252.0, 161096.0, 217680.0]  [439288.0, 161140.0, 217760.0]  
149695111  [436628.0, 164176.0, 217560.0]  [436528.0, 164092.0, 217560.0]  
15959535   [436560.0, 163892.0, 216520.0]  [436636.0, 163820.0, 216480.0

In [32]:
lower_bound, upper_bound, pre_ann.info['lower_bound'], len(df)

(array([438744., 146480., 220780.]),
 array([439020., 146588., 220980.]),
 [38904, 36396, 40],
 61)

In [4]:
pre_ann.info['spatial'][0]

{'chunk_size': [1024, 1024, 1024],
 'grid_shape': [13, 7, 10],
 'key': 'spatial0',
 'limit': 2994,
 'sharding': {'@type': 'neuroglancer_uint64_sharded_v1',
  'data_encoding': 'gzip',
  'hash': 'murmurhash3_x86_128',
  'minishard_bits': 0,
  'minishard_index_encoding': 'gzip',
  'preshift_bits': 10,
  'shard_bits': 0}}

In [21]:
np.floor((np.array([5820.0, 1050.0, 4850.0])-pre_ann.info['lower_bound'])/[1024,1024,1024])

array([5., 0., 3.])

In [6]:
pre_ann.info['upper_bound']

[13140.0, 7380.0, 10530.0]

In [14]:
pre_ann.info['lower_bound']+np.array(pre_ann.info['spatial'][0]['chunk_size'])*[6,3,2]

array([6724., 3522., 3038.])

In [3]:
pre_ann.get_relationships()

['rel_structure_id', 'rel_experiment_id']

In [4]:
pre_ann.get_property_names()

['injection_volume',
 'transgenic_line',
 'structure_abbrev',
 'structure_name',
 'gender',
 'structure_color']

In [5]:
pre_ann.properties

[AnnotationPropertySpec({"description": "injection_volume", "id": "injection_volume", "type": "float32"}),
 AnnotationPropertySpec({"description": "transgenic_line", "enum_labels": ["nan", "Rbp4-Cre_KL100", "Slc6a4-Cre_ET33", "Vipr2-Cre_KE2", "Rasgrf2-T2A-dCre", "Emx1-IRES-Cre", "Gpr26-Cre_KO250", "Slc6a4-CreERT2_EZ13", "Erbb4-T2A-CreERT2", "Trib2-F2A-CreERT2", "Fezf1-T2A-dCre", "Efr3a-Cre_NO108", "Slc17a6-IRES-Cre", "Cux2-IRES-Cre", "Esr1-2A-Cre", "Ppp1r17-Cre_NL146", "Slc6a5-Cre_KF109", "Ntng2-IRES2-Cre", "Cart-Tg1-Cre", "Gnb4-IRES2-Cre", "Glt25d2-Cre_NF107", "Sim1-Cre_KJ18", "Grik4-Cre", "Cck-IRES-Cre", "Grm2-Cre_MR90", "Th-Cre_FI172", "Plxnd1-Cre_OG1", "Slc18a2-Cre_OZ14", "Slc6a3-Cre", "Syt17-Cre_NO14", "Prkcd-GluCla-CFP-IRES-Cre", "Slc32a1-IRES-Cre", "Adcyap1-2A-Cre", "Cnnm2-Cre_KD18", "Ntrk1-IRES-Cre", "Satb2-Cre_MO23", "A930038C07Rik-Tg1-Cre", "Calb1-T2A-dgCre", "Tlx3-Cre_PL56", "Chat-IRES-Cre-neo", "Drd1a-Cre_EY262", "Grp-Cre_KH288", "Lypd6-Cre_KL156", "Kcng4-Cre", "Tac1-IRES2-

In [6]:
pre_ann.coordinate_space

CoordinateSpace({'x': [np.float64(1e-06), 'm'], 'y': [np.float64(1e-06), 'm'], 'z': [np.float64(1e-06), 'm']})

In [7]:
all_ids = pre_ann.get_all_annotation_ids()
all_ids

array([100147785, 100147853, 100147861, ..., 666909423, 671463542,
       671464291], dtype='>u8')

In [8]:
ann=pre_ann.get_by_id(all_ids[0])
ann

{'injection_volume': np.float32(0.1759717),
 'transgenic_line': np.uint16(0),
 'structure_abbrev': np.uint16(54),
 'structure_name': np.uint16(54),
 'gender': np.uint16(0),
 'structure_color': array([255, 144, 159], dtype=uint8),
 'padding15': array([0], dtype=uint8),
 'structure_id': array([1020], dtype=uint64),
 'experiment_id': array([100147785], dtype=uint64),
 'point': array([7600., 3380., 7070.], dtype=float32)}

In [9]:
df =pre_ann.get_by_relationship('structure_id', ann['structure_id'][0])
df

injection_volume   transgenic_line structure_abbrev  \
ID                                                               
267999740          0.302530         Grik4-Cre               PO   
183011353          0.200614         Grik4-Cre               PO   
174781014          0.166800               nan               PO   
100147785          0.175972               nan               PO   
292212456          0.039326         Grik4-Cre               PO   
182515576          0.045167      Gal-Cre_KI87               PO   
182892855          0.025026  Slc18a2-Cre_OZ14               PO   
180708524          0.015272               nan               PO   
301674988          0.009943  Slc18a2-Cre_OZ14               PO   

                              structure_name gender  structure_color  \
ID                                                                     
267999740  Posterior complex of the thalamus      M  [255, 144, 159]   
183011353  Posterior complex of the thalamus      M  [255, 144, 159]   
174781014  Posterior complex of the thalamus      M  [255, 144, 159]   
100147785  Posterior complex of the thalamus      M  [255, 144, 159]   
292212456  Posterior complex of the thalamus      F  [255, 144, 159]   
182515576  Posterior complex of the thalamus      M  [255, 144, 159]   
182892855  Posterior complex of the thalamus      M  [255, 144, 159]   
180708524  Posterior complex of the thalamus      M  [255, 144, 159]   
301674988  Posterior complex of the thalamus      F  [255, 144, 159]   

          padding15                     point  
ID                                             
267999740       [0]  [7540.0, 2400.0, 6990.0]  
183011353       [0]  [7340.0, 3550.0, 6870.0]  
174781014       [0]  [7440.0, 3600.0, 6920.0]  
100147785       [0]  [7600.0, 3380.0, 7070.0]  
292212456       [0]  [7560.0, 3450.0, 7110.0]  
182515576       [0]  [6830.0, 3760.0, 7370.0]  
182892855       [0]  [7230.0, 3980.0, 7070.0]  
180708524       [0]  [7350.0, 3930.0, 7040.0]  
301674988       [0]  [7430.0, 4110.0, 7440.0]

In [10]:
df =pre_ann.get_by_relationship('structure_id', ann['structure_id'][0], get_relationships=True)
df

injection_volume   transgenic_line structure_abbrev  \
ID                                                               
267999740          0.302530         Grik4-Cre               PO   
183011353          0.200614         Grik4-Cre               PO   
174781014          0.166800               nan               PO   
100147785          0.175972               nan               PO   
292212456          0.039326         Grik4-Cre               PO   
182515576          0.045167      Gal-Cre_KI87               PO   
182892855          0.025026  Slc18a2-Cre_OZ14               PO   
180708524          0.015272               nan               PO   
301674988          0.009943  Slc18a2-Cre_OZ14               PO   

                              structure_name gender  structure_color  \
ID                                                                     
267999740  Posterior complex of the thalamus      M  [255, 144, 159]   
183011353  Posterior complex of the thalamus      M  [255, 144, 159]   
174781014  Posterior complex of the thalamus      M  [255, 144, 159]   
100147785  Posterior complex of the thalamus      M  [255, 144, 159]   
292212456  Posterior complex of the thalamus      F  [255, 144, 159]   
182515576  Posterior complex of the thalamus      M  [255, 144, 159]   
182892855  Posterior complex of the thalamus      M  [255, 144, 159]   
180708524  Posterior complex of the thalamus      M  [255, 144, 159]   
301674988  Posterior complex of the thalamus      F  [255, 144, 159]   

          padding15 structure_id experiment_id                     point  
ID                                                                        
267999740       [0]       [1020]   [267999740]  [7540.0, 2400.0, 6990.0]  
183011353       [0]       [1020]   [183011353]  [7340.0, 3550.0, 6870.0]  
174781014       [0]       [1020]   [174781014]  [7440.0, 3600.0, 6920.0]  
100147785       [0]       [1020]   [100147785]  [7600.0, 3380.0, 7070.0]  
292212456       [0]       [1020]   [292212456]  [7560.0, 3450.0, 7110.0]  
182515576       [0]       [1020]   [182515576]  [6830.0, 3760.0, 7370.0]  
182892855       [0]       [1020]   [182892855]  [7230.0, 3980.0, 7070.0]  
180708524       [0]       [1020]   [180708524]  [7350.0, 3930.0, 7040.0]  
301674988       [0]       [1020]   [301674988]  [7430.0, 4110.0, 7440.0]

In [11]:
df = pre_ann.get_all_annotations()
df.head()

injection_volume transgenic_line structure_abbrev  \
ID                                                             
100147785          0.175972             nan               PO   
100147853          0.073548             nan             VISp   
100147861          0.138880             nan              CA1   
100148142          0.122178             nan             RSPv   
100148143          0.114309             nan               DG   

                              structure_name gender  structure_color  \
ID                                                                     
100147785  Posterior complex of the thalamus      M  [255, 144, 159]   
100147853                Primary visual area      M    [8, 133, 140]   
100147861                          Field CA1      M   [126, 208, 75]   
100148142   Retrosplenial area, ventral part      M   [26, 166, 152]   
100148143                      Dentate gyrus      M   [126, 208, 75]   

          padding15 structure_id experiment_id                     point  
ID                                                                        
100147785       [0]       [1020]   [100147785]  [7600.0, 3380.0, 7070.0]  
100147853       [0]        [385]   [100147853]  [9440.0, 1220.0, 8630.0]  
100147861       [0]        [382]   [100147861]  [6640.0, 1650.0, 7510.0]  
100148142       [0]        [886]   [100148142]  [6830.0, 1260.0, 6160.0]  
100148143       [0]        [726]   [100148143]  [6690.0, 2690.0, 6190.0]

In [12]:
some_ids = df.index[0:10]
pre_ann.get_by_ids(some_ids)

injection_volume transgenic_line structure_abbrev  \
ID                                                             
100147785          0.175972             nan               PO   
100147853          0.073548             nan             VISp   
100147861          0.138880             nan              CA1   
100148142          0.122178             nan             RSPv   
100148143          0.114309             nan               DG   
112229814          0.189563             nan           SSp-ul   
112425523          0.200597             nan               PH   
112595376          0.089164             nan             RSPv   
112672268          0.099276             nan               DG   
112672974          0.399350             nan             ENTm   

                                      structure_name gender  structure_color  \
ID                                                                             
100147785          Posterior complex of the thalamus      M  [255, 144, 159]   
100147853                        Primary visual area      M    [8, 133, 140]   
100147861                                  Field CA1      M   [126, 208, 75]   
100148142           Retrosplenial area, ventral part      M   [26, 166, 152]   
100148143                              Dentate gyrus      M   [126, 208, 75]   
112229814     Primary somatosensory area, upper limb      M   [24, 128, 100]   
112425523             Posterior hypothalamic nucleus      M    [255, 76, 62]   
112595376           Retrosplenial area, ventral part      M   [26, 166, 152]   
112672268                              Dentate gyrus      M   [126, 208, 75]   
112672974  Entorhinal area, medial part, dorsal zone      M    [50, 184, 37]   

          padding15 structure_id experiment_id                     point  
ID                                                                        
100147785       [0]       [1020]   [100147785]  [7600.0, 3380.0, 7070.0]  
100147853       [0]        [385]   [100147853]  [9440.0, 1220.0, 8630.0]  
100147861       [0]        [382]   [100147861]  [6640.0, 1650.0, 7510.0]  
100148142       [0]        [886]   [100148142]  [6830.0, 1260.0, 6160.0]  
100148143       [0]        [726]   [100148143]  [6690.0, 2690.0, 6190.0]  
112229814       [0]        [369]   [112229814]  [5830.0, 1520.0, 7640.0]  
112425523       [0]        [946]   [112425523]  [7600.0, 4930.0, 6120.0]  
112595376       [0]        [886]   [112595376]  [8350.0, 1540.0, 6970.0]  
112672268       [0]        [726]   [112672268]  [9050.0, 3890.0, 8800.0]  
112672974       [0]        [926]   [112672974]  [9350.0, 4720.0, 8830.0]

In [5]:
box_size = [500, 500, 500]
point = ann.get('point', ann.get('point_a',None))
lower_bound = point-box_size
upper_bound = point+box_size

df=pre_ann.get_annotations_in_bounds(lower_bound=lower_bound,
                                     upper_bound=upper_bound)
df

cleft_score        score         id  autapse  \
ID                                                        
15959460         150.0   516.035522   15959460        0   
15959581         179.0    12.401705   15959581        0   
149695039          0.0   356.254761  149695039        0   
15959542         150.0   347.875031   15959542        0   
15959580         155.0   250.698074   15959580        0   
15959565         147.0   240.189438   15959565        0   
15959574          74.0   137.183212   15959574        0   
15959499         163.0    40.697067   15959499        0   
15959490         130.0   371.010071   15959490        0   
15959575          79.0   421.441040   15959575        0   
15959515         147.0  1123.519531   15959515        0   
15959467         148.0   856.287720   15959467        0   
15959554         153.0   430.270447   15959554        0   
15959564          75.0   128.977783   15959564        0   
15959482         147.0  2171.692383   15959482        0   
15959511         149.0   472.981384   15959511        0   
15959466         162.0   424.376160   15959466        0   
15959500         149.0   688.379272   15959500        0   
15959462         176.0    77.578064   15959462        0   
15959489         145.0   179.880798   15959489        0   
15959513         150.0   372.870026   15959513        0   
15959500         149.0   688.379272   15959500        0   
15959535         148.0   645.653015   15959535        0   

                                  point_a                         point_b  
ID                                                                         
15959460   [436024.0, 163820.0, 216200.0]  [436040.0, 163708.0, 216200.0]  
15959581   [436492.0, 164016.0, 216680.0]  [436468.0, 164040.0, 216720.0]  
149695039  [436868.0, 163636.0, 216800.0]  [436888.0, 163764.0, 216800.0]  
15959542   [436660.0, 164060.0, 216520.0]  [436768.0, 164048.0, 216520.0]  
15959580   [436524.0, 163980.0, 216680.0]  [436576.0, 163956.0, 216720.0]  
15959565   [436608.0, 164048.0, 216640.0]  [436708.0, 164024.0, 216640.0]  
15959574   [436440.0, 163932.0, 216680.0]  [436404.0, 163872.0, 216680.0]  
15959499   [436340.0, 163824.0, 216320.0]  [436356.0, 163676.0, 216320.0]  
15959490   [436516.0, 164000.0, 216320.0]  [436600.0, 163980.0, 216320.0]  
15959575   [436604.0, 164096.0, 216680.0]  [436708.0, 164124.0, 216680.0]  
15959515   [436612.0, 163984.0, 216520.0]  [436716.0, 163948.0, 216520.0]  
15959467   [436208.0, 163892.0, 216280.0]  [436308.0, 163824.0, 216280.0]  
15959554   [436576.0, 163944.0, 216600.0]  [436676.0, 163876.0, 216600.0]  
15959564   [436412.0, 163828.0, 216640.0]  [436400.0, 163752.0, 216640.0]  
15959482   [436476.0, 163812.0, 216480.0]  [436504.0, 163720.0, 216520.0]  
15959511   [436384.0, 163780.0, 216440.0]  [436396.0, 163676.0, 216440.0]  
15959466   [436096.0, 163848.0, 216200.0]  [436148.0, 163744.0, 216240.0]  
15959500   [436168.0, 163864.0, 216320.0]  [436196.0, 163760.0, 216320.0]  
15959462   [436192.0, 163980.0, 216200.0]  [436308.0, 164012.0, 216160.0]  
15959489   [436504.0, 163924.0, 216360.0]  [436588.0, 163840.0, 216280.0]  
15959513   [436508.0, 163880.0, 216400.0]  [436588.0, 163784.0, 216360.0]  
15959500   [436168.0, 163864.0, 216320.0]  [436196.0, 163760.0, 216320.0]  
15959535   [436560.0, 163892.0, 216520.0]  [436636.0, 163820.0, 216480.0]